### ISSUE TITLE
not working on hetzner

### ISSUE THREAD

**Issue by vahidx4r4x** [Null3rror/OpenVPN-over-Proxy#3]
Hi, I've tried your script on my vultr's server and it works perfectly.
but on my hetzner server connection will restart for infinite times.
I've checked the "openvpn-server@server.service" service with systemctl and found that service is loaded but its status is on `activating` mode, and there is a error with red line: `--status /run/openvpn-server/status-server.log --status-version 2 --suppress-timestamps --config server.conf`
your script is awesome but it needs some improvements
can you figure out the error?

TNX

**Comment by Null3rror** [comment]
Hi, thanks for giving it a try.
I had been using my script on a Hetzner server for nearly a year and a half and never had this issue. 
Can you tell me how I can reproduce this error?
I don't have a server at hand right now to try to fix this. Do you want to further discuss this matter on Discord or Skype?

**Comment by vahidx4r4x** [comment]
hi that was my fault. I used journalctl and found out that port 443 was used by a process 
and found that the process was ocserv.
problem solved

**Comment by Null3rror** [comment]
Great!
Feel free to leave a star so we can help out more people.
Cheers.
