### ISSUE TITLE
getting "cp: cannot stat" errors on Ubuntu 22.04

### ISSUE THREAD

**Issue by akromjon** [Null3rror/OpenVPN-over-Proxy#7]
cp: cannot stat 'pki/ca.crt': No such file or directory
cp: cannot stat 'pki/private/ca.key': No such file or directory
cp: cannot stat 'pki/issued/server.crt': No such file or directory
cp: cannot stat 'pki/private/server.key': No such file or directory
cp: cannot stat 'pki/crl.pem': No such file or directory
chown: cannot access '/etc/openvpn/server/crl.pem': No such file or directory

**Comment by Null3rror** [comment]
I'm archiving this repository so I have to close your issue.
